name: note
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.5
  crypto: ^3.0.5
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  fancy_shimmer_image: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_highlighting: ^0.9.0+11.8.0
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  lottie: ^3.1.2
  onesignal_flutter: ^5.2.5
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  staggered_grid_view_flutter: ^0.0.4
  supabase_flutter: null
  uuid: ^4.5.0

dev_dependencies:
  flutter_launcher_icons: "^0.14.1"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/notes_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_background: "#1f1d2b"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/lang/
    - assets/animations/
    - assets/images/
    - assets/images/onBoarding/
    - assets/images/folder.png
    - assets/svgs/folder.svg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
